# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{global_collect}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Timon Karnezos"]
  s.date = %q{2010-04-12}
  s.description = %q{Gives minimally intrusive access to Global Collect's payment processing API. 
Currently implements a very small segment of the full API but is built with 
extensibility in mind.
}
  s.email = %q{timon.karnezos@gmail.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "README.markdown",
     "VERSION"
  ]
  s.homepage = %q{http://github.com/timonk/global_collect}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A Ruby client to the Global Collect API}
  s.test_files = [
    "spec/api_client_spec.rb",
     "spec/builders/insert_order_with_payment/order_spec.rb",
     "spec/builders/insert_order_with_payment/payment_spec.rb",
     "spec/field_validator_spec.rb",
     "spec/global_collect_spec.rb",
     "spec/request_models/base_spec.rb",
     "spec/request_models/insert_order_with_payment/credit_card_online_payment_spec.rb",
     "spec/request_models/insert_order_with_payment/hosted_credit_card_online_payment_spec.rb",
     "spec/requests/base_spec.rb",
     "spec/requests/composite_spec.rb",
     "spec/requests/insert_order_with_payment_spec.rb",
     "spec/responses/base_spec.rb",
     "spec/responses/insert_order_with_payment/credit_card_online_payment_response_methods_spec.rb",
     "spec/responses/insert_order_with_payment/hosted_merchant_link_payment_response_methods_spec.rb",
     "spec/responses/succcess_row_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0.5.2"])
      s.add_runtime_dependency(%q<builder>, [">= 2.0"])
    else
      s.add_dependency(%q<httparty>, [">= 0.5.2"])
      s.add_dependency(%q<builder>, [">= 2.0"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0.5.2"])
    s.add_dependency(%q<builder>, [">= 2.0"])
  end
end

